#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

latestTime=$(foamListTimes -latestTime)

# Remove the 0 folder
rm -r 0/
# Use the 0.dp folder as inital conditions (with pressureJump)
cp -r 0.dp/ 0/
# copy the U field from the latestTime
cp $latestTime/U 0
# Change name of fvOptions
mv constant/fvOptions constant/fvOptions_U

rm log.decomposePar
rm log.simpleFoam
rm log.reconstructPar
rm -r processor*
mv postProcessing/inlet_Vflow/0/surfaceFieldValue.dat postProcessing/inlet_Vflow/0/surfaceFieldValue_old.dat


runApplication decomposePar
# Run the hydraulic simulation
runParallel $(getApplication)
runApplication reconstructPar -latestTime

# Change name of fvOptions
mv constant/fvOptions_U constant/fvOptions
